#include "PlatformConfig.h"


extern PlatformConfig_Descriptor vectorQueue_Config_Desc;
extern PlatformConfig_Descriptor OS_Scheduler_Config_Desc;
extern PlatformConfig_Descriptor OS_StackAllocator_Config_Desc;
extern PlatformConfig_Descriptor OS_DeviceManager_Config_Desc;



